# Aggregations in Tensorflow

In [22]:
import tensorflow as tf
import numpy as np

base_tensor = tf.constant([[-2, -4],
                            [-5, -8],
                            [-3, -6]])

# Create Random tensor
random_tensor = tf.constant(np.random.randint(0, 100, size=50))
random_tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([36, 93, 92, 53, 65, 84, 25, 67, 99,  8,  4, 28, 88, 71, 13, 71, 69,
       40, 74, 41,  8, 74, 99, 74, 25, 34, 30, 70, 35,  6,  4, 66, 17, 69,
       56, 60, 32, 94, 68, 75, 92, 72, 57,  3, 55,  6, 46, 74, 71, 22])>

In [2]:
# Get the Absolute
tf.abs(base_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 8],
       [3, 6]], dtype=int32)>

In [7]:
# Get Minimum of Tensor
tf.reduce_min(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [8]:
# Get the Max of Tensor
tf.reduce_max(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=95>

In [9]:
# Get the mean of Tensor
tf.reduce_mean(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [25]:
# Get sum of Tensor
tf.reduce_sum(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2615>

In [31]:
# Convert to Real because Variance can't take int32 dtype
cast_random_tensor = tf.cast(random_tensor, dtype=tf.float64)

# Get the Variance of Tensor
tf.math.reduce_variance(cast_random_tensor)

<tf.Tensor: shape=(), dtype=float64, numpy=840.73>

In [30]:
# Get Standard of Tensor
tf.math.reduce_std(cast_random_tensor)

<tf.Tensor: shape=(), dtype=float64, numpy=28.995344453894663>

In [34]:
# Another way to get veriance by importing `tensorflow_probability`
import tensorflow_probability as tfp

tfp.stats.variance(cast_random_tensor)

<tf.Tensor: shape=(), dtype=float64, numpy=840.73>