# Matrix Multiplication Training from 022-matrix-multiplication

Use `tf.linalg.matmul`, `tf.matmul` or `tf.tensordot` to Matrix Multiply Tensors

In [7]:
import tensorflow as tf

# Tensor 3-dimensional (3, 3)
tf_1 = tf.constant([[1,2,5],
                    [7,2,1],
                    [3,3,3]])

# Tensor 2-diminsional (2, 3)
tf_2 = tf.constant([[3,5],
                    [6,7],
                    [1,8]])

# Matrix Multiplication
tf.linalg.matmul(tf_1, tf_2)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

## What happens to Matmul if tensors are the same shape?

In [13]:
# Tensor 2-dimensional (3, 2)
tf_1 = tf.constant([[1,2],
                    [7,2],
                    [3,3]])

# Throws: Matrix size-incompatible
# tf.linalg.matmul(tf_1, tf_2)

# Use Transpose to make it compatible with matmul (Flips Axis)
print("Transpose Matmul Result: %s \n" % (tf.linalg.matmul(tf.transpose(tf_1), tf_2)))

# Use Reshape to shape the tensor (Gives different results to transposing)
print("Reshape Matmul Result: %s \n" % (tf.linalg.matmul(tf.reshape(tf_1, [2, 3]), tf_2)) )

Transpose Matmul Result: tf.Tensor(
[[48 78]
 [21 48]], shape=(2, 2), dtype=int32) 

Reshape Matmul Result: tf.Tensor(
[[22 75]
 [27 55]], shape=(2, 2), dtype=int32) 

