# Squeezing Tensors

In [12]:
import tensorflow as tf

# Set Seed
tf.random.set_seed(42)

In [11]:
x = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
x

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68346524, 0.63335645, 0.11209059, 0.66795564, 0.19320524,
           0.7738247 , 0.30257404, 0.54104376, 0.15997136, 0.86424243,
           0.07796359, 0.47208202, 0.7635459 , 0.16621494, 0.8566421 ,
           0.6076417 , 0.3988105 , 0.58646846, 0.43992782, 0.78578746,
           0.11294258, 0.0522927 , 0.37244356, 0.9440285 , 0.5861299 ,
           0.8659171 , 0.89619863, 0.25605762, 0.99150443, 0.6677054 ,
           0.34679163, 0.9336711 , 0.2081958 , 0.26547658, 0.9693227 ,
           0.6023991 , 0.64630103, 0.49673605, 0.5857309 , 0.59391606,
           0.35118365, 0.6889124 , 0.5734278 , 0.50454414, 0.00818479,
           0.45328104, 0.1011436 , 0.10269737, 0.40232027, 0.8582916 ]]]]],
      dtype=float32)>

In [13]:
x.shape

TensorShape([1, 1, 1, 1, 50])

In [21]:

x_squeezed = tf.squeeze(x)

x_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68346524, 0.63335645, 0.11209059, 0.66795564, 0.19320524,
       0.7738247 , 0.30257404, 0.54104376, 0.15997136, 0.86424243,
       0.07796359, 0.47208202, 0.7635459 , 0.16621494, 0.8566421 ,
       0.6076417 , 0.3988105 , 0.58646846, 0.43992782, 0.78578746,
       0.11294258, 0.0522927 , 0.37244356, 0.9440285 , 0.5861299 ,
       0.8659171 , 0.89619863, 0.25605762, 0.99150443, 0.6677054 ,
       0.34679163, 0.9336711 , 0.2081958 , 0.26547658, 0.9693227 ,
       0.6023991 , 0.64630103, 0.49673605, 0.5857309 , 0.59391606,
       0.35118365, 0.6889124 , 0.5734278 , 0.50454414, 0.00818479,
       0.45328104, 0.1011436 , 0.10269737, 0.40232027, 0.8582916 ],
      dtype=float32)>